### ISSUE TITLE
Typo in PHP tag

### ISSUE THREAD

**Issue by nlegaillart** [dryoo/dokuwiki-template-kajukkd#4]
Hi,

I found this little typo that prevents the hamburger menu to work (it return `Undefined constant "php"`):

https://github.com/dryoo/dokuwiki-template-kajukkd/blob/2e37a63b8e8b2f08a461f402d30af8387eb9f0d6/main.php#L235

By correcting it to `<?php`, menu works again.

Regards,

**Comment by dryoo** [comment]
ok corrected
